### ISSUE TITLE
Android: Campaigns are not shown

### ISSUE THREAD

**Issue by deyupopp** [usabilla/usabilla-u4a-xamarin#24]
We tried to create the bindings dll and import it in our Android application. Passive form works well, but campaigns are not shown. See attached sample project.
Steps to reproduce:
- link a Xamarin Android app with Usabilla 
- create a campaign for the app id
- replace app id UsabillaApp and event name in MainActivity in the sample project with the required data
- run the application
- tap on the fab to invoke Usabilla.Instance.SendEvent()

The campaign is never shown, and I'm not sure how to test whether the event was not sent, or it was sent but the there is an issue displaying the campaign.

[UsabillaTest.zip](https://github.com/usabilla/usabilla-u4a-xamarin/files/3380704/UsabillaTest.zip)

Edited sample project to not contain our application data

**Comment by andreaiori** [comment]
Hi @deyupopp,

Thank you so much for including your test app. 

The problem seems to be related to the way you are sending the campaign event to our SDK. Upon inspecting the code, it looks like you are passing a form ID instead of an event name. 

![2019-07-10 at 4 45 PM](https://user-images.githubusercontent.com/43612835/60979321-c88eba00-a332-11e9-854a-5f97145b571e.jpg)

You can define the event name directly in Usabilla under the targeting options for the campaign. 

![image](https://user-images.githubusercontent.com/43612835/60979430-025fc080-a333-11e9-82ca-b53dc520e7cb.png)

**Comment by deyupopp** [comment]
Hello. First, sorry for the mistake in the sample project. It's true that I used our appId as parameter, but the campaign still don't appear after I send an event. 
We previously used Usabilla with a self-made binding library, and the campaigns worked, and after updating to this one they stopped working. I posted another issue that was clarified to me, so I will try to come back to you tomorrow, after we use the NuGet package instead of local reference of the DLL, as that might be the issue. 

Sorry for the mistake again, and thank you.

**Comment by deyupopp** [comment]
I retried with the bindings library, and the campaigns still don't display. We have a campaign that should be displayed when the event is triggered four times, for 100% of users. It works with our old binding library, but doesn't work with this one. I uninstalled the app after testing with each one, so it's not related to the user already seeing the campaign. Thank you.

**Comment by torkvell** [comment]
Hi @deyupopp ,

Thanks for your patience on this. Could you please share the campaign name and account name by sending an email to [support@usabilla.com](support@usabilla.com). We can then try to reproduce this with your configuration. 

Looking forward to your reply.
